apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crypto-service.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/ebms_crypto"
  SPRING_DATASOURCE_USERNAME: "ebms"
  KEYSTORE_PATH: {{ .Values.env.KEYSTORE_PATH | default "/app/keystores/keystore.p12" | quote }}
