apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crypto-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crypto-service.labels" . | nindent 4 }}
  annotations:
    # KRITIEK: In productie gebruik HSM of external-secrets voor keystore credentials
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.SPRING_DATASOURCE_PASSWORD | quote }}
  KEYSTORE_PASSWORD: {{ .Values.secret.KEYSTORE_PASSWORD | quote }}
