apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crypto-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crypto-service.labels" . | nindent 4 }}
automountServiceAccountToken: false
