apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cpa-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cpa-service.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/ebms_cpa"
  SPRING_DATASOURCE_USERNAME: "ebms"
