apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cpa-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cpa-service.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.SPRING_DATASOURCE_PASSWORD | quote }}
