apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ebms-orchestrator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ebms-orchestrator.labels" . | nindent 4 }}
automountServiceAccountToken: false
